### ISSUE TITLE
Anniversary card

### ISSUE THREAD

**Issue by cob94440** [berkansezer77/home-assistant#7]
Hello Berkans,
With latest ho 2023.12.0, it doesn't work anymore.

I replaced in template sensor claendar.list_events with  calendar.get_events
But it dosn't work.

Service seems.
With list_events response was :

```
events:
  - start: "2023-12-26"
    end: "2023-12-27"
    summary: Anniversaire Chris
```

with get_events it's : 

```
calendar.anniversaires:
  events:
    - start: "2023-12-26"
      end: "2023-12-27"
      summary: Anniversaire Chris
```
